### ISSUE TITLE
Interpretation of CFR

### ISSUE THREAD

**Issue by jalonsomartinez** [ImperialCollegeLondon/covid19model#1]
Sorry to step in here, but saw the article and wanted to share something.

From the code it seems that you assume that CFR is the probability of dying given the infection.
However, you should take into account two opposite effects:

1) While death data may be rather clean (not really, but let's leave this), number of cases is a mess. I can talk from my country (Spain). This renders CFR useless, as it is greatly overestimated by this effect and it is not even consistent through time.

2) Even with clean data, I think you are forgetting that due to the death lag and epidemic growth, Observed CFR greatly underestimated by an opposite effect:

Maybe an example helps:

Assumptions:
Real mortality: 3%
Total cases day 0: 100
Daily increase 30%

What we see:
Total cases day 10 : 100*1.3^10= 1400
Total Deaths day 10: 100*.03= 3
CFR observed at day 10: 3/1400=0.2%

Observed CRF is 14 times lower than real mortality.

regards,
Jaime

**Comment by tmellan** [comment]
The case data is unreliable as you say, so we fit to death data only and not reported cases.

The CFR used is not estimated from the reported cases in each European country, it comes from  citation 11, which is here https://www.medrxiv.org/content/10.1101/2020.03.09.20033357v1.full.pdf . These CFR are weighted by the age pyramid of each European country, and give final values you can have a look at in the file weighted_fatality.csv in /data.

The lag between cases and deaths is accounted for and discussed in sections 6 and 8 of the report: https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-Europe-estimates-and-NPI-impact-30-03-2020.pdf 

Hope that is helpful

**Comment by oriori** [comment]
> have a look at in the file weighted_fatality.csv in /data.

How come the weighted_fatality for France is higher than for Italy even though Italy has an older population? (If this is not the proper place for this discussion, please let me know).

Thanks

**Comment by s-mishra** [comment]
France's contact patterns are somewhat less heterogeneous than Italy's which really drops off in the elderly, so given we've standardized to an R0, we expect higher attack rates in the elderly in France, which means overall more elderly people end up getting infected compared to Italy! Also to clarify that in our analysis we use IFR, not CFR.  Again to point the values are taken from this Lancet ID  paper https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30243-7/fulltext#tables

**Comment by jalonsomartinez** [comment]
Ok, thank you. I was misled by a comment in the code.

If I understand it well, you use a single value, not a bracket for the IFR. Is that right?

Thanks again.

**Comment by ilarele** [comment]
Hello,

Thank you for the study and for making the code available!
I want to add Romania in the list of the countries and I got stuck when computing **weighted_fatality** column in weighted_fatality.csv, because I don't know how to adjust its value using the **contact information** (which is most similar with Poland I guess - for which socialmixr has survey data from POLYMOD).

```
# age intervals
reported_cases = np.array([40, 63, 221, 452, 671, 500, 305, 169, 39])
population = np.array([1939134, 2069083, 2174981, 2621141, 3076100, 2508724, 2559619, 1482916, 932860])

# from reference 11
ifr_china = [0.0016, 0.007, 0.031, 0.084, 0.16, 0.60, 1.9, 4.3, 7.8] / 100

ar = reported_cases / population
ifr = (ar[5] / ar) * ifr_china
weighted_fatality = (population/sum(population) * ifr).sum()
```

It will be great if you can give me a hint!

Thank you,
Elena

**Comment by nlhuong** [comment]
Hello Authors,

I also thank you for distributing the open-source code with the paper.
I would like to second Elena's request to the full formula (or code w/ input data) you use for computing `AR` and `ifh` (for obtaining weighted_fatality.csv). It would make it possible for researchers to use your models for countries outside of the pool of 11 that you chose.

Thank you!
Lan

**Comment by s-mishra** [comment]
Hi guys, as said we are using fatality rates from Verity et al.  Once we could get hold of real calculation and data we will certainly open source it.
