### ISSUE TITLE
Code for Impact of non-pharmaceutical interventions (NPIs) to reduce COVID19 mortality and healthcare demand

### ISSUE THREAD

**Issue by ebanhamhall** [ImperialCollegeLondon/covid19model#10]
Hi,

Thanks for your great work. I've really enjoyed reading it.

Is there a repository or other way of accessing the code used in the paper from 16th March? I emailed Neil Ferguson but no answer - almost certainly way too busy with COVID.

Would be nice to take a look at the methods used there.

Thanks,

Ed

**Comment by s-mishra** [comment]
Thanks a lot,
Neil's code is not out yet. It will be soon.

**Comment by ebanhamhall** [comment]
Thanks Swapnil - do you have an approximate date on when this will be available?
