### ISSUE TITLE
R value in base.stan

### ISSUE THREAD

**Issue by sgt101** [ImperialCollegeLondon/covid19model#102]
Hello, 

am I correct that the mu value in base.stan is the R0 infection rate? 

I looked at the reference in the code - to Lui et-al 2020 ISTM paper. The mean of the estimates is 3.28; why was that chosen rather than the median, and why were the outliers not excluded?

**Comment by s-mishra** [comment]
Given that is just a prior and we have distribution around it all plausible values that data wants is available. It is not a fixed value but a normal centered at 3.28 with sigma as kappa so we have big variations around it covered.

**Comment by flaxter** [comment]
Just to add, mu is the parameter for R0, not the time varying reproduction
number R(t).
