### ISSUE TITLE
Full run: execution halted after 8 hours - no figures 

### ISSUE THREAD

**Issue by Tresnia** [ImperialCollegeLondon/covid19model#103]
Hi Swapnil, 
As discussed by email, I am logging an issue request here. 
To summarise: 
Managed to run for Italy only. Figures and results produced as expected. 
However, then tried to execute the full run a few times. Produced the same error each time:
'Execution halted' 
(see screenshot for details)

No figures were produced in the Figures folder. 

Get the following error messages after 8 hours of run: 
"Error: geom_line range requires the following missing aesthetics: x, ymin, ymax
Execution halted
Error: Error while plotting covariate size effects! Code: 1
Execution halted"

Would have expected the full script to run and produce full set of figures 

See attached screenshots of 6 main warnings and error messages: 
<img width="1440" alt="Screenshot 2020-05-11 at 23 23 19" src="https://user-images.githubusercontent.com/18242086/81618505-659d0200-93df-11ea-948f-ebed0f22f7b7.png">
<img width="1440" alt="Screenshot 2020-05-11 at 23 23 09" src="https://user-images.githubusercontent.com/18242086/81618521-6a61b600-93df-11ea-827a-ee1292c8d88c.png">

 - OS: Mac

**Additional context**
Tried to run the code 5 times since Friday morning. Execution halted every time. 
Same errors occur each time, after roughly 8 hours.

**Comment by s-mishra** [comment]
Hi @Tresnia ,

May I know what command are you running and have you checked you have all the dependencies to run that are listed in enviornment.yml?

Please run this from terminal `Rscript base.r base -D` or first set debug environment variable to TRUE and then source base.r. 
This is a debug run which won't take more than 3 mins to run.  I can still get everything to run on windows, mac and ubuntu.

If you still get an error either paste it here.

**Comment by s-mishra** [comment]
Other thing is may I get a full description of your environment please?

**Comment by s-mishra** [comment]
As discussed over chat, issue is essentially ggplot being at old version. Update ggplot to version 3.3.0 or later and things should be fine.
