### ISSUE TITLE
Smoothing reported death data

### ISSUE THREAD

**Issue by RoryOConor** [ImperialCollegeLondon/covid19model#111]
There are several issues with daily reported death data: Weekly trends including delays in reporting at weekends. One off issues eg addition of multiple care home deaths at irregular intervals. 

It should be relatively simple to smooth the weekly trends. For irregular additions, these extra deaths could be proportionally redistributed back to the previous irregular addition.

The smoothed death distribution can then be better compared against the modelled distribution.

**Comment by s-mishra** [comment]
look at usa code we allow that now for you to test. read_data functions
