### ISSUE TITLE
new release for US report?

### ISSUE THREAD

**Issue by bbolker** [ImperialCollegeLondon/covid19model#112]
I note that the last update is from 8 days ago, but there's not obviously US-specific content here, and some of the plots on the website have data going up to May 16.  Is this the latest version or is there updated code on a private repo somewhere that will be mirrored here?  Thanks ...

**Comment by s-mishra** [comment]
The exact code for US will be here by Monday just cleaning before the official release. In the mean time you can look at code for Report 20/21 which are very much on similar lines. Yes US code will be released soon to make sure exacr things can be reproduced. Thanks for your patience

**Comment by verretor** [comment]
> The exact code for US will be here by Monday

It's Tuesday.

**Comment by s-mishra** [comment]
Code has been released here 29942a8
