### ISSUE TITLE
Data analysis for subdivision per country

### ISSUE THREAD

**Issue by pablodz** [ImperialCollegeLondon/covid19model#113]
I would like to analyze [countries in Latin America](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica) but I don't know how to do epidemic modelling. So I'm requesting an analyze per subdivision per country as a help.

**Comment by ettieunwin** [comment]
Hi. Take a look at our code for Brazil as a starting point - it refers to the models presented in this report https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-21-brazil/
