### ISSUE TITLE
Prediction for Indian data, only Infection part

### ISSUE THREAD

**Issue by arindomchakraborty** [ImperialCollegeLondon/covid19model#12]
Hi,
I am a newcomer to STAN. I tried to predict the spread in India using the code. I modified the code accordingly. But it is still not working. I am interested in the prediction of infections only.

Any help in this regard will be highly appreciated.
Stay safe.
with best wishes,
Arindom

[Code_India.zip](https://github.com/ImperialCollegeLondon/covid19model/files/4425414/Code_India.zip)

**Comment by s-mishra** [comment]
Hi @arindomchakraborty ,

Without death data and interventions data this model won't work for you. Also we need estimates of IFR for India
