### ISSUE TITLE
conda env geofacet

### ISSUE THREAD

**Issue by antoine4ucsd** [ImperialCollegeLondon/covid19model#120]
I am having trouble with geofacet in the proposed conda environnement
I can't figure out how to install it properly in my new env and I see it is not in the list of available dependencies...
Any suggestions?

I run
``
Rscript base-usa.r --full
``
my message:
``
Error in library(geofacet) : there is no package called ‘geofacet’
``
but it is not possible to install it with the following...
``
conda install r-geofacet
``
any suggestions?

thank you so much

**Comment by s-mishra** [comment]
geofacet you will need to install from CRAN.
