### ISSUE TITLE
posterior parameter values for alpha, alpha_region, and alpha_state

### ISSUE THREAD

**Issue by antoine4ucsd** [ImperialCollegeLondon/covid19model#121]
Hi
Would it be possible to extract/ouput the posterior parameter values for alpha, alpha_region, and alpha_state (linking mobility to transmission)? any advices would be very much appreciated!
thank you and congrats for this impressive work,

a

**Comment by s-mishra** [comment]
For sure. just do out <- rstan::extract(fit). And now out has all the samples for the required parameters. which you can use as out$alpha, out$alpha_region and out$alpha_state.
