### ISSUE TITLE
alpha_region

### ISSUE THREAD

**Issue by antoine4ucsd** [ImperialCollegeLondon/covid19model#122]
Hi
First, congrats again for this impressive work!
Working on the usa data: I was able to extract the vectors for the alpha regions 
If I get it right, the alpha[,1:8] correspond to the regional intercept and the alpha[,9:16] to the mobility.
what I don't get is how the regional intercept and moblity are used in the equation for Rt. Could you help clarify this point?

<img width="827" alt="Rt" src="https://user-images.githubusercontent.com/18502631/86045145-054e3800-ba00-11ea-8c01-7dafdb578330.png">

thank you+++

**Comment by s-mishra** [comment]
Thanks, you are mistaken on how alpha_region is structured. It's dimensions are [chains, regions, regional_features]. which means alpha_region[,1,] is the intercept and alpha_region[,2,] is the coeff for averageMobility. Now  X_partial_regional is of dimensions [states,N2,regional_features], which means X_partial_regional is [states,N2,2] matirx where  X_partial_regional[,,1] is the intercept and  X_partial_regional[,,2] is averageMobility

PS: I have assumned you have passed formula_regional as '~ 1 + averageMobility'.

**Comment by antoine4ucsd** [comment]
Thank you for clarifying the matrix structure. My confusion came from the equation printed in the report, where I interpreted Y(t,m) and alpha_region(r(m)) both as scalar signals. Could you help clarify what the coefficient and intercept components represent?

![equation](https://user-images.githubusercontent.com/18502631/86198139-c7d6d100-bb0b-11ea-9a02-0b70c9d8dc2b.png)

On a related note - the first dimension of alpha_region is 4000 (chains, as you referred to it). We are interpreting this as a timespan, measured in units smaller than days. is this correct?

thank you so much,

**Comment by s-mishra** [comment]
that is incorrect, it is the number of chains the sampler has run.
