### ISSUE TITLE
Typo in mean time from onset-to-death

### ISSUE THREAD

**Issue by mbevand** [ImperialCollegeLondon/covid19model#124]
Your research states the mean onset-to-death time as 17.8 days, however there are a few instances of the code in this repository where you use 18.8 instead of 17.8. I assume these are typos?

```
./Brazil/code/preprocessing-subnation-brazil.r:  ONSET_to_DEATH=18.8
./Italy/code/utils/process-covariates-italy.r:  mean2 <- 18.8; cv2 <- 0.45 # onset to death
./base_general.r:mean2 = 18.8; cv2 = 0.45 # onset to death
./Python/src/dataset.py:                mean = 18.8
./Python/src/dataset.py:                mean_2 = 18.8
```

PS: I came across this bug as part of my work on forecasting Florida deaths. I want to implement the gamma distribution of onset-to-death to improve the accuracy of my model: https://github.com/mbevand/florida-covid19-line-list-data

**Comment by tmellan** [comment]
Hi, 17.8 and 18.8 days were both based on early estimates from Verity et al. Both estimates have overlapping CrI. 18.8 corrects censoring but has wider credible intervals I believe. Which was better was not 100% clear early on. As more data becomes available estimates of this value are improving, and I think shorter than 18.8 is now more appropriate in many instances, but this depends on things like location etc. Thanks.
