### ISSUE TITLE
Added to Open Source COVID-19

### ISSUE THREAD

**Issue by WeileiZeng** [ImperialCollegeLondon/covid19model#15]
Thanks for your work to help the people in need! Your site has been added to the Open-Source-COVID-19 page, which collects open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

http://open-source-covid-19.weileizeng.com/

Cheers!

**Comment by WeileiZeng** [comment]
Is the project working on UK data only?

**Comment by flaxter** [comment]
Hi. You might be interested in our report:
https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-13-europe-npi-impact/

We currently cover 11 European countries.

Regards,
Seth

**Comment by WeileiZeng** [comment]
@flaxter nice work. Added!
