### ISSUE TITLE
Number of deaths in Norway is wrong

### ISSUE THREAD

**Issue by Sunnivabl** [ImperialCollegeLondon/covid19model#17]
Thank you for working on and sharing this code!
But as already mentioned in Norwegian newspapers, the death-numbers for Norway is completely wrong. I don't know where the responsibility to update the edcd-database lies, but it is clearly not updated correctly.  (ref article: https://www.dagbladet.no/nyheter/tror-viruset-har-smittet-over-40-000-nordmenn/72317406)
I hope other countries work harder to provide the right numbers, since so many use this report as the closest you get to the truth on this epidemic.
KR Larsen

**Comment by s-mishra** [comment]
Hi @Sunnivabl , thanks for this. Unfortuanetly for us there is no real way to know which data is correct and which is not.

**Comment by s-mishra** [comment]
We will surely look into sources you pointed for our next model update.
