### ISSUE TITLE
Clarification surrounding counterfactual estimation

### ISSUE THREAD

**Issue by willtebbutt** [ImperialCollegeLondon/covid19model#2]
I was wondering if it would be possible to get some clarification around the precise methodology used to obtain the counterfactual results in table 2 of [your most recent report](https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-Europe-estimates-and-NPI-impact-30-03-2020.pdf).

In particular, is that the case that

1. inference was performed in a model with time-varying R_{t, m} to obtain the posterior over R_{0, m}, which was subsequently utilised as a distribution over R{0, m} in a counterfactual model, from which samples are generated assuming R_{t, m} = R_{0, m} for all t, or
2. two separate models were fit, one in which R_{t, m} varies, and one in which R_{0, m} does not,

(presumably 2 would estimate a lower R_{0, m} for the counterfactuals than 1), or something else was done?

I ask because page 13 para 2 of the report begins `To understand the impact of interventions, we fit a counterfactual model without the interventions and compare this to the actual model.`, suggesting that multiple models have been fit, which doesn't match with what I was imagining that you're doing in table 2.

Apologies in advance if I've missed the bit of the report where you explain this in detail!

**Comment by s-mishra** [comment]
Hi there, thanks for raising the question. As you can see in the stan code section generated quantities, we essentially fit only one model and use the posterior over R{0,m} for the counterfactual model (line 95 as posterior over R{0.m} is same as mu[m]).

**Comment by willtebbutt** [comment]
Hi @s-mishra thanks for clearing things up so promptly -- much appreciated.
