### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/covid19model#21]
To leverage community engagement as much as possible I suggest adding a CONTRIBUTING.md file. GitHub has a [good introduction](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors).

Letting people know what they can do and how they can most effectively help you will get the most out of open sourcing your work.

My last interfering suggestion I promise ;)

**Comment by s-mishra** [comment]
Addressed via commit #27
