### ISSUE TITLE
Interpreting the `EpidemicStart` variable

### ISSUE THREAD

**Issue by lukeanto** [ImperialCollegeLondon/covid19model#22]
Hello,

thank you for your work! I'm a newcomer in Bayesian models, so I found your code really interesting.

The `EpidemicStart` data seems no to so clear to me: I figured it out as the day when you considered started the epidemic in each country, but all the array element has the same value, 31 (it is calculated as `index1+1-index2`, but `index2 = index1-30`). 

You use these values as a cut-off for deaths in the STAN model: as you stated in the COVID Report 13, you only include deaths when they are more than 10 for each country. But in this way the model includes all deaths data from the 31st day on, for all countries, so may you can check this variable.

Regards,

Luca

**Comment by s-mishra** [comment]
Hi @lukeanto , Not all the array values are the same. Only the values for the first 6 days are the same and it is not 31 for all the countries. Epidemic start date is essentially used to make sure the deaths in the initial period is not assigned to epidemic in the country as those are from the imported cases for European countries.
