### ISSUE TITLE
Possible to keep data updated and continuously update the figures?

### ISSUE THREAD

**Issue by zach-hensel** [ImperialCollegeLondon/covid19model#26]
Is it possible to produce daily reports using this model to show how estimates of post-intervention transmission and total percentage of population vary with data up to a certain day, and to update the data to be current?

I see many people citing the percent infected as of March 28 and post-intervention R figures, so I think there's a value in making sure the estimates are informed by the most recent data, and seeing how the estimates change as new data is added.

**Comment by harrisonzhu508** [comment]
This is being implemented using a CI pipeline via GitHub pages. Expected deployment of v1 is within hours.

**Comment by zach-hensel** [comment]
Awesome -- thanks!

**Comment by harrisonzhu508** [comment]
@zach-hensel slight delay in the deployment - within days now

**Comment by s-mishra** [comment]
We have deployed a website now lol at #v2.0
