### ISSUE TITLE
How to reproduce results / run the code?

### ISSUE THREAD

**Issue by HughParsonage** [ImperialCollegeLondon/covid19model#3]
I applaud you for your work and for making the code available. That said, I'm not sure how to run the code. I infer in the below line that I'm supposed to run this from the command line with arguments (or at least that if no arguments are provided then `base` is run), but I'm not sure whether that's the right approach or if it is what arguments I should pass to `Rscript`.

https://github.com/ImperialCollegeLondon/covid19model/blob/144356c4dc487ed7f42fa86bc6f2210c6399ecc7/base.r#L21

There are other inputs that are apparently needed (like the environment variable `PBS_JOBID`), but I'm not sure what they do.

Can you provide one or two examples in the `README.md`?

Thanks again.

**Comment by s-mishra** [comment]
Hi there, thanks a lot for pointing this out. I have updated the readme now to make it relatively easy to run our code. Look at commit f379e92
