### ISSUE TITLE
Discrepancy between implementation and paper?

### ISSUE THREAD

**Issue by torfjelde** [ImperialCollegeLondon/covid19model#34]
I'm currently trying to reproduce the model in [another PPL](https://turing.ml/) and I'm slightly confused when comparing the model and code.

[In the paper (p. 20)](https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/2020-03-30-COVID19-Report-13.pdf) you can find the following:
![image](https://user-images.githubusercontent.com/11074788/78614990-81593980-7870-11ea-9356-a98ce98f421a.png)
while in the code we have
https://github.com/ImperialCollegeLondon/covid19model/blob/5c756a69f9d73e28ffe37a15b6cccc157dcf5160/stan-models/base.stan#L67-L68
https://github.com/ImperialCollegeLondon/covid19model/blob/5c756a69f9d73e28ffe37a15b6cccc157dcf5160/stan-models/base.stan#L34
which means the code is implementing `Exponential(0.03)` and `Exponential(1 / τ)` rather than `Exponential(0.03)` and `Exponential(τ)` as specified in the paper (or with inverse parameters, depending on which parameterisation you're using in the paper).

So I'm wondering if this is a mistake in the code or just a typo in the paper?:)

Also, from the above snippet from the paper, it seems to me that `y[m]` should be a random vector of length `num_impute` or `N0` (6 in paper) for _each_ `m`, while in the code all the imputed values seem to be the _same value_:
https://github.com/ImperialCollegeLondon/covid19model/blob/5c756a69f9d73e28ffe37a15b6cccc157dcf5160/stan-models/base.stan#L39
Is this correct?

Thanks!

(Btw, really appreciate you open-sourcing this!)

**Comment by s-mishra** [comment]
Hi @torfjelde, thanks for pointing this out. There is a typo in the paper.  It should have been exponential(1/tau). Also yes all imputed values are same for all N0 day but it is specific to a country by virtue of y being a vector of length M (where M is the  total number of countries)

**Comment by torfjelde** [comment]
Aight :+1: Thanks for the reply!:)
