### ISSUE TITLE
Hospitalization

### ISSUE THREAD

**Issue by philipus** [ImperialCollegeLondon/covid19model#37]
I am wondering whether hospitalization is included or not. I guess not...

Is that possible to include hospitalization as you did in a former Report 9? This is from the society perspective very important because I guess that measures is only driven by the projection (maximum) of the hospitalization.

**Comment by nlhuong** [comment]
I think you can model the counts of hospitalized in a similar way as deaths are in the paper. You just need to substitute the prior for pi, to a reasonable distribution for the sum of time from infection to symptoms and time from symptoms to hospitalization. Also switch from `ifr` to `ihr` (infected-to-hospitalized-ration). The estimates of unadjusted ihr are also in the reference [11].

**Comment by s-mishra** [comment]
As said @nlhuong  we could do it. However, right now we are not able to take this because of work load and availability of data. We might come back to it later.

**Comment by philipus** [comment]
In France we have pretty good Data https://www.data.gouv.fr/en/datasets/donnees-hospitalieres-relatives-a-lepidemie-de-covid-19/
