### ISSUE TITLE
theoretical predictions for R0

### ISSUE THREAD

**Issue by philipus** [ImperialCollegeLondon/covid19model#40]
Where is the part in the Code to get the theoretical predictions for R0?

**Comment by s-mishra** [comment]
extract Rt from out/fit like out$Rt

**Comment by philipus** [comment]
apply((as.matrix(out$Rt[,1,])),2,median) for the intial R0?

**Comment by gustavdelius** [comment]
@philipus , for the initial R0 you should look in `out$mu`.

**Comment by philipus** [comment]
oh , I thought mu is the one from the fit to the data and not the theoretical one. Sorry that i am bothering you so heavily.

**Comment by flaxter** [comment]
mu is the parameter giving our estimate of the initial R0 for each country.
It is inferred from the data. Can you clarify what you mean by "theoretical
one"? Are you asking what prior we place on mu?

**Comment by philipus** [comment]
Figure 18 in Report 13
