### ISSUE TITLE
Comment on trends in cumulative infection predictions and Rt

### ISSUE THREAD

**Issue by zach-hensel** [ImperialCollegeLondon/covid19model#44]
I looked at predicted cumulative infections for the March 28 and April 9 runs. Of countries with some sort of lockdown (all of them ex-Sweden), 5 show lower predicted percentages infected on April 9 than on March 28. There is a positive correlation between the ratio of the April 9 and March 28 infection estimates and the day in March of lockdown. Qualitatively there are similar trends for post-lockdown Rt: all countries except Norway Rt>1 on March 28; all countries except Belgium Rt<1 on April 9.

Given that cumulative infections and Rt are important data points for policy (the main things I've seen cited from this work), could you comment on that? I wonder if a lag of transmission in home/work post-lockdown-day could be added to the model?

**Comment by s-mishra** [comment]
Hi @zach-hensel  as we get more data our estimates changes even for the past and you get more reliable information. If you compare the results between updates you would have noticed the shrinkage of credible intervals. Stay tuned on the website, we will have our comments and interpretation of results soon.
