### ISSUE TITLE
 g++.exe: error: : No such file or directory

### ISSUE THREAD

**Issue by Oliver-Sheaky** [ImperialCollegeLondon/covid19model#5]
Hello, 

When attempting to run the code, specifically line 201

`m = stan_model(paste0('stan-models/',StanModel,'.stan'))`

 I get the following error;

`Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! 
g++.exe: error: sheaky/Documents/R/R-3.6.3/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp: No such file or directory
g++.exe: error: sheaky/Documents/R/R-3.6.3/library/StanHeaders/include: No such file or directory
g++.exe: error: sheaky/Documents/R/R-3.6.3/library/RcppEigen/include: No such file or directory
make: *** [C:/Users/OLIVER~1/DOCUME~1/R/R-36~1.3/etc/x64/Makeconf:215: file17041f307c4a.o] Error 1`

The correct path to the library is C:/Users/oliver sheaky/Documents/R/R-3.6.3/library, I am assuming it is failing to handle the space in my username? 

I followed the instructions [here](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) for setting up RStan in case that was causing the issue, but that didn't resolve it.

Apologies if its a super simple fix I have never used RStan before.

Thanks in advance for your help,
Oliver

**Comment by harrisonzhu508** [comment]
@Oliver-Sheaky  We are creating a Docker image atm at #4  so you will just need a few lines of code to run our models soon.

Hmm I'm not too sure too be honest with that bug, not sure how the g++ compiler deal with spaces in file paths in WindowsOS. Anything on Google that resembles your error?

**Comment by Oliver-Sheaky** [comment]
@harrisonzhu508 Thanks for the quick reply I had a google around but couldn't find anything related or similar to my error, unfortunately. 

I was more interested in using the code to learn about a new way of modelling in R, rather than the output generated.

**Comment by Oliver-Sheaky** [comment]
I found the issue, the StanHeaders package version is somehow ahead of the Rstan version.

The solution is here https://discourse.mc-stan.org/t/compilation-error-with-stanheaders-no-such-file-or-directory/13007.

I highly recommend searching [here](https://discourse.mc-stan.org/c/interfaces/rstan/29) for any RStan related errors.

Oliver
