### ISSUE TITLE
Simulate the Risk of lifting measures 

### ISSUE THREAD

**Issue by philipus** [ImperialCollegeLondon/covid19model#52]
**Is your feature request related to a problem? Please describe.**
Great people from Imperial, I think you need to publish a report 15 what happend when you lift measures. Your report 9 had such a good inpact on poletician. I am scared the poletician do not understand the dynamics when we lift measures on a much bigger basis of infectiuous people without noticing any change for 14 days because of the delay from exposed -> infectious -> hospital -> ... 

**Describe the solution you'd like**
extension of the measure table with a new column containing either implemented of lifted at date X

**Describe alternatives you've considered**
With an entended version of a SEIR Model. But people from Imperial, it does not matter how bust it matters who publishs the topics.

**Comment by s-mishra** [comment]
Hi @philipus, thanks for your suggestion. We are looking into a lot of extensions and working hard to be as acuurate as we can be.

**Comment by d-Slava** [comment]
this topic is of crucial importance, as intervension have to be lifted at some point and same actors could look at Imperial for help on guidance and prove of concept.

On this way I see in particularly following challenges:
1. further enhancement of herd immunity modelling. which has a dependency of proper data (I'm not sure how reliable are cases data even for 50..59 bucket used in Verity et al's study, used in ifr and hence ultimately impacting performed population adjustment)
2. seasonality modelling. naively expecting ifr dependency from season. it naturally puts time pressure on this topic, to be able to assess promptly an optimal timing for lifting
3. may still need to model health system saturation impact I'm affraid
