### ISSUE TITLE
Reports not displaying on old Android browser

### ISSUE THREAD

**Issue by dentarthur** [ImperialCollegeLondon/covid19model#53]
**Describe the bug**

Only header and footer of reports display on an old Android Tablet browser.
No problem in Chrome on same Tablet

**To Reproduce**
"COVID-19 Planning Tools

Daily updated estimates for Europe

...

Find out more >"

Works fine in Chrome on Android Tablet but not on default browser on same Tablet.

Default Android browser has link broken from:

https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-planning-tools/

to:

https://imperialcollegelondon.github.io/covid19estimates/#/details/United_Kingdom

Shows footer and top banner with drop down menus but not working.

Same problem for link from README in this repo at:

"You can look at our results here"

in:

https://github.com/ImperialCollegeLondon/covid19model

 to:

https://imperialcollegelondon.github.io/covid19estimates

Works ok in Chrome but not in default Android browser.

**Expected behavior**

Tools link shows UK data in Chrome browser.
README link shows introduction.

**Desktop (please complete the following information):**
Android System Webview 80.0.3987.132 on Samsung Galaxy 10.5 SM-T800 Android 5.02

**Additional context**

Seems bizarre but I double checked after SHIFT refresh of cache.

Page footer as well as header is visible.

Suggested Fix:

Probably not worth fixing the actual problem. Could just add a note in header and/or footer:

"If page not displaying properly update Chrome browser"

**Comment by s-mishra** [comment]
Thanks for pointing this out. for now, we will leave it as something we won't fix. We might come to it later when there is more time to do so.
