### ISSUE TITLE
Discrepancy for Spain

### ISSUE THREAD

**Issue by d-Slava** [ImperialCollegeLondon/covid19model#54]
Hi Swapnil / All,

Thank you for all your efforts in this project.

Just joining this space and have few questions. Sorry if some of them were already adressed.

1st one being why in v2.0 at April 12th predicted deaths for Spain are far outside of 95% CI for quite a few recent dates? I understood that given nb of cases and interventions age, Spainish data were intensively used for model calibration..

thx and rgds
Slava

**Comment by s-mishra** [comment]
Hi @d-Slava sorry for the discrepancy, the credible interval is for the mean of the estimate not the observation. We have a negative-binomial likelihood that has an extra variance term in there, which if drawn covers the observation.

**Comment by d-Slava** [comment]
Hi Swapnil,
thank you for promp feedback
I meant CI of the estimate (shown at 2nd graph at https://imperialcollegelondon.github.io/covid19estimates/#/details/Spain)
Am I correct to understand that same relative change in % of Rt due to interventions is still assumed for all countries..? for me it s a bit of counterintuitive, as I'd rather expect that invervention with same strictness and enforceabily will results in same absulute level of Rt post intervention. So now when we have more historical data, we have to fit it by country. Which is especially needed for Sweden and UK to evidence impact of milder interventions.

**Comment by s-mishra** [comment]
So for this model, this is what we had in assumptions. We are soon releasing an update where each country will have its specific factor too. But still will borrow strength from other countries. Currently, we are full pooling and the next update would be partial pooling. Keep an eye it will be out less than a week.
