### ISSUE TITLE
v2.0 vs v1.0 results dynamic explanation

### ISSUE THREAD

**Issue by d-Slava** [ImperialCollegeLondon/covid19model#55]
Hi All,

Also it would be good to have some high level explanation of few very visible changes in results of v2.0 at April 12th vs Report 13 (v1.0 at March 30th):
- significant descrease of % of total population infected estimate mean for Italy and Spain;
- dropping of Rt estimate post lockdown below 1 for most of countries.
If it s mainly due to new data or model improvements

thx and rgds
Slava

**Comment by s-mishra** [comment]
Hi @d-Slava  the improvements are attributed to both more data which means more signal and some model improvements. You can look at new model in the technical document we have in the repository.
