### ISSUE TITLE
Providing the source for IFR calculations (code, attack rates, contact matrices)

### ISSUE THREAD

**Issue by payoto** [ImperialCollegeLondon/covid19model#57]
Low priority (I think)

**Is your feature request related to a problem? Please describe.**
Trying to expand the model to new countries or regions, accurate estimation of the IFR is needed and not simple.

**Describe the solution you'd like**
If you could open the source and the data used in the IFR calculations already included in the repository? Either in this repo, or in a separate one?

At minimum it would be nice to have the contact matrices to not have to redo the work that was
done in report 12 finding all the country specific data to process.

**Describe alternatives you've considered**
Attempting to reproduce it, but this seems like it would be so much easier with the input data.

**Comment by s-mishra** [comment]
Hi @payoto, unfortunately we also get this data directly from verity.et.al. We do not have control over their release. They are working on getting it out but it is not as straightforward as what we assume.
