### ISSUE TITLE
Provide output as text files.

### ISSUE THREAD

**Issue by g-rutter** [ImperialCollegeLondon/covid19model#59]
**Is your feature request related to a problem? Please describe.**
It's quite costly to obtain the output of this model at the moment. One has to prepare their system to run it, then do so for a few hours.

**Describe the solution you'd like**
If you guys are running it most days anyway, couldn't you just provide the output? I see the graphs on your website, but no raw data output from anything I can see. It would be very helpful!

**Describe alternatives you've considered**
Putting the graph into one of those graph digitisers. Or just running it myself.

**Additional context**
Just a thank-you for your work on this!

**Comment by becare-rocket** [comment]
How long does it take to run?  I'm running it now.  Only took about 15 minutes to setup.  What kind of machine are you using.  I will benchmark mine when it finishes...

**Comment by becare-rocket** [comment]
Approximate benchmark is it takes about 40 minutes on an old mac-mini.  I would bet it would run about 4x faster on a newer machine.  I give this just so that other users running for the first time can have an idea on how much time it would take.

**Comment by becare-rocket** [comment]
G-Rutter -- I think the run takes about an 40 minutes on a macmini, although I am not sure I get the same results as they are presenting.  To get the data in tabular form, find make-table.r and uncomment the commented lines that do a write.csv.  You can change the target directory from "figures" to something else you prefer.  I suggest setting up the batch job to run once around 1300Z so as to capture the current day's Euro CDC data.  After that -- no need to resort to reading pixel's from a chart.  If you are lucky you can get the Imperial College Team to do it for you, but it is not that hard.  I wrote a small r function to translate their csv's back into the format that my R model expects transposing the rows and columns.

**Comment by s-mishra** [comment]
Hi @g-rutter  sure we are working on it to provide csv or just a model that runs in like an hr or so. @becare-rocket  that 40 min is the debug run not the full run.

**Comment by jarib** [comment]
@g-rutter I have a script here that generates a CSV per country from the model output: https://github.com/jarib/covid19model/blob/6e4a0e36e220333d43b8f6d75480b2e16cbb9240/make-country-csvs.r

@s-mishra Let me know if you'd like a pull request that drops this under `web/` somewhere.

**Comment by g-rutter** [comment]
@s-mishra Thanks for your response. I am glad to hear that. I think the issue should remain open if your advice is "we are working on it" - that would be the usual approach.

@jarib Thanks for this. It should be helpful to the Imperial team.

**Comment by payoto** [comment]
Hello @jarib, 
Lovely feature! It was on my todo list, I'm gonna pull it into my fork on branch https://github.com/payoto/covid19model/tree/community-contribs , if you don't mind. 
I'm maintaining a branch of community features on my fork feel free to have a look for something of interest.

@s-mishra It would be nice to reopen this and tag it with the `community` label as we discussed the other day, similarly with PR #66 which seems related.
