### ISSUE TITLE
Add 10 Latin American countries; consider curfew and partial quarantines

### ISSUE THREAD

**Issue by leonardo-calcagno** [ImperialCollegeLondon/covid19model#68]
Dear all, thank you for your work. My name is Leonardo Calcagno, I am a Doctor in Economics from the University of Orleans (France) and am currently working in Argentina's National Audit Office (AGN). 
**Is your feature request related to a problem? Please describe.**
I worked on running the model with the Latin American countries /territories that reported 10 or more COVID19 deaths by 15 Aprtil 2020: Argentina, Brazil, Chile, Colombia, Dominican Republic, Ecuador, Mexico, Panama, Peru and Puerto Rico. The full process, from cloning version 1 up to where I am right now, is on my **Github Page https://github.com/leonardo-calcagno/covid19model_latam/tree/latam**

**Describe the solution you'd like**
- I added interventions on those 10 Latin American countries in the data folder, with the sources I found for determining intervention dates
- Classified first interventions as done for Europe, then Latin-American specific interventions (**curfew and partial or regional quarantine**)
- Computed IFR ratios based on UNPOPS population data (but without taking into account social contact matrices);
- Corrected the source data for Puerto Rico with data taken from https://github.com/CSSEGISandData. Corrected the COVID-19-up-to-date csv to bring observations up to 31/12/2019 for all countries (to avoid bugs); 
- Added a forecast plot with **counter-factual estimated deaths**, taken from the estimated.deaths.cf variable. Since it's version 1 it is unreliable for more advanced stages of the epidemic, when some immunity starts to build up, but it remains useful for the early stages (it shows **Brazil deaths followed counter-factual estimated deaths up to the first week of April**). 
- Ended-up commenting-out Ecuador due to probably under-reported deaths, as claimed by the mayor of Guayaquil  https://www.elcomercio.com/actualidad/guayaquil-enfermos-muertos-viteri-coronavirus.html. She claims there were on March 2020 1500 additional deaths in the city of Guayaquil when compared with March 2019; that 50 municipal civil servants died from COVID19; and that reported deaths from COVID19 are false because not enough tests are done to dead people to determine whether COVID19 was the cause of death. Daily number of deaths are thus likely an order of magnitude higher than currently reported. 

**Describe alternatives you've considered**
 I ran three types of simulations: 
1- pooling Latin American and European countries together, with version 1 covariates 
2- pooling only among Latin American countries, with version 1 covariates
3- pooling only among Latin American countries, with School Closure, Public events banned, lockdown, curfew and partial quarantine as covariates

I found when pooled with European countries, Latin American lockdown measures brought contagion rates below 1; whereas, when pooled only between Latin American countries, lockdown measures were less effective. I am not sure whether this is due to differences in classification, to the fact European countries are in a more advanced stage of the epidemic, or whether lockdown measures are less effective in Latin America. 

More generally, why not **distinguish between hard and soft lockdown**, or partial and full quarantine, in European countries as well? 

**Additional context**
Here I put figures for Brazil respectively pooled with European countries; pooled only between Latin American countries; and pooled between Latin American countries with specific covariates. 
**Brazil**
**Pooled with European countries**
<img width="1382" alt="Capture d’écran 2020-04-15 à 19 36 52" src="https://user-images.githubusercontent.com/7986102/79395675-8bee8f80-7f50-11ea-890a-a43ed2cb0605.png">
<img width="1102" alt="Capture d’écran 2020-04-15 à 19 38 59" src="https://user-images.githubusercontent.com/7986102/79395782-c8ba8680-7f50-11ea-9875-943e3bced208.png">
Counterfactual
<img width="1104" alt="Capture d’écran 2020-04-15 à 19 40 03" src="https://user-images.githubusercontent.com/7986102/79395855-f273ad80-7f50-11ea-9129-88acb81935e5.png">

**Pooled with Latin American countries, same covariates as version 1**
<img width="1380" alt="Capture d’écran 2020-04-15 à 19 45 30" src="https://user-images.githubusercontent.com/7986102/79396179-b3922780-7f51-11ea-997e-64b77eac5f50.png">
<img width="1098" alt="Capture d’écran 2020-04-15 à 19 46 26" src="https://user-images.githubusercontent.com/7986102/79396237-d1f82300-7f51-11ea-88c2-edd78c673897.png">
Counterfactual
<img width="1104" alt="Capture d’écran 2020-04-15 à 19 47 06" src="https://user-images.githubusercontent.com/7986102/79396270-e9cfa700-7f51-11ea-90b1-82b375cf9983.png">

**Pooled with Latin American countries, specific covariates**
<img width="1379" alt="Capture d’écran 2020-04-15 à 19 49 07" src="https://user-images.githubusercontent.com/7986102/79396742-f56f9d80-7f52-11ea-810c-59af23292848.png">
<img width="1098" alt="Capture d’écran 2020-04-15 à 19 55 16" src="https://user-images.githubusercontent.com/7986102/79396799-0d472180-7f53-11ea-83f5-49cef7200191.png">
Counterfactual 
<img width="1099" alt="Capture d’écran 2020-04-15 à 19 55 42" src="https://user-images.githubusercontent.com/7986102/79396847-1fc15b00-7f53-11ea-9b00-bc965b440355.png">

**Comment by s-mishra** [comment]
Hi @leonardo-calcagno, great work :) It is not that we have not tried partial and full lockdowns but having them as measures means for each country you need to curate a lot more and more importantly each partial lockdown is different depending on each region. 

On your second point why with Europe you more decline compared without it. The answer is this is a full pooling model and the full pool model assumes the same behavior across different regions hence countries with more advanced epidemics drive the results. However, we will soon release a partial
pool model which will solve the issue effectively.

On the third point of IFR calculations, any calculation that doesn't go through verity.et.al full methodology of using a contact matrix is not something we can merge to the master. However, my hope is with partial pooling model out, this can be added as a different folder.

**Comment by leonardo-calcagno** [comment]
Hi @s-mishra  thank you for your swift and useful answers. I understand, I look forward to the partial pooling model, if at that point I can lend you a hand feel free to contact me.
