### ISSUE TITLE
Add 44 US States & District of Columbia

### ISSUE THREAD

**Issue by goldfrank** [ImperialCollegeLondon/covid19model#69]
I have extended your model to 44 US States and the District of Columbia, using data from [Johns Hopkins](https://github.com/CSSEGISandData) and adapting it for the input format of your model.

For state-specific IFR, I used the European-country IFR averge, since test coverage in USA is insufficient.

Due to some hard-coding related to the European data, I used new `_us.r` files derived from the original. My progress is at a [forked repository](https://github.com/goldfrank/covid19model). I am uploading my results [here](https://covid.ignatius.coffee).

If the authors are interested in the simple addition of "United States," this would be a relatively straightforward change. My intention going forward is to add a factor (k=7) for "partial lockdown" to represent situations where large municipalities locked down before the entire state.

**Comment by s-mishra** [comment]
Hi @goldfrank, great work. It is not that we have not tried partial and full lockdowns but having them as measures means for each country you need to curate a lot more and more importantly each partial lockdown is different depending on each region. 

On the point of IFR calculations, any calculation that doesn't go through verity.et.al full methodology of using a contact matrix is not something we can merge to the master.

**Comment by dsjoerg** [comment]
Hi @goldfrank some volunteer colleagues and I are interested in doing US as well, care to collaborate?  I am reachable at dsjoerg@gmail.com
