### ISSUE TITLE
"Total infected" wording?

### ISSUE THREAD

**Issue by r3m0t** [ImperialCollegeLondon/covid19model#70]
https://mrc-ide.github.io/covid19estimates/#/total-infected

Hi, I read the caption "Posterior model estimates of percentage of total population infected as of 2020-04-15." before reading the sentence "We report the total percentage of the population infected over the course of the pandemic not the population as of now."

Can it be rephrased to "Posterior model estimates of percentage of total population infected over the course of the pandemic. Estimates as of 2020-04-15." ?

**Comment by s-mishra** [comment]
Hi @r3m0t , for sure! Will do it today and then close this issue

**Comment by s-mishra** [comment]
Solved with the commit 865806ff6f7afb393
