### ISSUE TITLE
Docker image run on MacOS ends up in error

### ISSUE THREAD

**Issue by usptact** [ImperialCollegeLondon/covid19model#73]
**Describe the bug**

**To Reproduce**
$ docker run covid19model

**Expected behavior**
Expected results folder populated and figures generated.

**Screenshots**
Error in compileCode(f, code, language = language, verbose = verbose) :
  Compilation ERROR, function(s)/method(s) not created! In file included from /usr/lib/R/site-library/RcppEigen/include/Eigen/Core:392,
                 from /usr/lib/R/site-library/RcppEigen/include/Eigen/Dense:1,
                 from /usr/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
                 from <command-line>:
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h:60:39: warning: ignoring attributes on template argument ‘__m128’ {aka ‘__vector(4) float’} [-Wignored-attributes]
   60 | template<> struct is_arithmetic<__m128>  { enum { value = true }; };
      |                                       ^
/usr/lib/R/site-library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h:61:40: warning: ignoring attributes on template argument ‘__m128i’ {aka ‘__vector(2) long long int’} [-Wignored-attributes]
   61 | template<> struct is_arithmetic<__m128i> { enum { value = true }; };
      |
Calls: stan_model ... cxxfunctionplus -> <Anonymous> -> cxxfunction -> compileCode
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/usr/lib/R/bin/R CMD SHLIB file6f80ddb.cpp 2> file6f80ddb.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
Calls: stan_model -> cxxfunctionplus -> sink

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Version 10.15.3

**Additional context**
N/A

**Comment by jmbrowne26** [comment]
I am getting the same issue when using conda to create the environment and then running base.r in Rstudio in Windows 10.

**Comment by s-mishra** [comment]
Hi @usptact, look here Stan has issues with MacOD Catalina 
https://github.com/stan-dev/rstan/wiki/Catalina-problems

**Comment by s-mishra** [comment]
Hi @jmbrowne26 , Can you give details of the issue not just a single line

**Comment by jmbrowne26** [comment]
Hi @s-mishra this is the error I get when **running in the terminal**:
Error in compileCode(f, code, language = language, verbose = verbose) :
  Compilation ERROR, function(s)/method(s) not created!       2 [main] make 15816 fork: child 8608 - died waiting for dll loa
ding, errno 11
make: fork: Resource temporarily unavailable
Calls: stan_model ... <Anonymous> -> <Anonymous> -> force -> cxxfunction -> compileCode
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/Users/j.browne/Documents/R/R-3.6.3/bin/x64/R CMD SHLIB file2c287ef35b3c.cpp 2> file2c287ef35b3c.cpp.err
.txt' had status 1
Error in sink(type = "output") : invalid connection
Calls: stan_model -> cxxfunctionplus -> sink
Execution halted

and when **running in the console** I get:
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file398030ec2db2.cpp:6:36: warning: ISO C99 requires whitespace after the macro name
 #define STAN__SERVICES__COMMAND_HPP#include <boost/integer/integer_log2.hpp>
                                    ^
make: *** [C:/Users/J5116~1.BRO/DOCUME~1/R/R-36~1.3/share/make/winshlib.mk:13: file398030ec2db2.dll] Error 127
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/Users/J5116~1.BRO/DOCUME~1/R/R-36~1.3/bin/x64/R CMD SHLIB file398030ec2db2.cpp 2> file398030ec2db2.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection

**Comment by dsjoerg** [comment]
I had a similar issue.  I worked around it by launching a Linux VM on AWS EC2 and running Docker there. :(
