### ISSUE TITLE
Contribute 50 state variant?

### ISSUE THREAD

**Issue by aolney** [ImperialCollegeLondon/covid19model#79]
I have data (intervention dates, IFRs) for all U.S. states plus my county.

I've run this through an earlier version of your model (I mirrored into a private repo after commit 10a42cfc444be562cb506290628f9bf6351ffc52).

Please let me know if/how you'd like me to contribute this back or keep it as a mirrored project (which I expect will be public shortly).

**Comment by aolney** [comment]
Just a follow up on the IFRs from my colleague

```
We used the age-specific IFRs in ICL Report 9 (Ferguson et al), which were 
described as adjusted to account for a non-uniform attack rate in the GB/US 
context. In the absence of a contact matrix for the US, we are forced to make 
the assumption (implicit in the ICL-9 model) that age-specific attack rates are 
similar in the US and GB contexts and are also similar across US states.

We then collated age group demographics for 50 states and Shelby Co, TN (our 
primary interest); these data were collected from the 2018 ACS 5-year estimates, 
which are the most current data available from the US census bureau. We took the 
weighted average of the age-specific IFRs in Ferguson et al, weighting by the 
population proportion in each age group. The resulting age- and 
demography-adjusted IFRs varied from 0.76% (Utah) to 1.35% (Florida).
```

**Comment by nealmcb** [comment]
Thanks. I'd love to see this extended to and updated for the United States and elsewhere.

Note also the related work at [The Metric We Need to Manage COVID\-19 – systrom](http://systrom.com/blog/the-metric-we-need-to-manage-covid-19/) with a [Jupyter notebook implementation](https://github.com/k-sys/covid-19/blob/master/Realtime%20R0.ipynb)

There are data sources from both [JHU](https://github.com/CSSEGISandData/COVID-19) and [CovidTracking.com](CovidTracking.com)

**Comment by dsjoerg** [comment]
Also interested!  Myself and some volunteer colleagues are available to work on this.

**Comment by s-mishra** [comment]
Version 6 has it now https://github.com/ImperialCollegeLondon/covid19model/tree/v6.0
