### ISSUE TITLE
Generation of alpha covar table failed!

### ISSUE THREAD

**Issue by dsjoerg** [ImperialCollegeLondon/covid19model#83]
**Describe the bug**
Running on Docker under Linux, it dies with `Generation of alpha covar table failed!`

**To Reproduce**
1. Set up Docker on Linux 2 AMI or AWS EC2 as per these [instructions](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html)
2. Run `docker run --rm -v $(pwd)/results:/var/model/results -v $(pwd)/figures:/var/model/figures harrisonzhu5080/covid19model:latest`
3. Wait 30 minutes (faster with more vCPUs probably)
4. Error message:
```
There were 50 or more warnings (use warnings() to see the first 50)
[1] "Make forecast table"
[1] "Running results/base-318697-stanfit.Rdata"
Error in `$<-.data.frame`(`*tmp*`, value, value = character(0)) : 
  replacement has 0 rows, data has 14
Calls: $<- -> $<-.data.frame
Execution halted
Error: Generation of alpha covar table failed! Code: 1
Execution halted
```
Full transcript [here](https://gist.github.com/dsjoerg/9abc670bb0ef946a6c13192ab4af1294)

**Expected behavior**
DNA code for a virus that, upon infecting a human, renders them immune to COVID-19.
Or, failing that, complete without errors.

**Comment by s-mishra** [comment]
Hi @dsjoerg , thanks for raising this. I will do the required update soon, by end of GMT day.

**Comment by s-mishra** [comment]
Hi @dsjoerg, the issue is with MAC. It should be fine either with new docker or refer here
https://github.com/stan-dev/rstan/wiki/Catalina-problems
