### ISSUE TITLE
I can't seem to get this to run locally on my mac

### ISSUE THREAD

**Issue by Kumereng** [ImperialCollegeLondon/covid19model#86]
This is my error message at the end: 
> covariate_size_effects_error <- system(paste0("Rscript covariate-size-effects.r ", filename,'-stanfit.Rdata'),intern=FALSE)
Loading required package: magrittr
This is bayesplot version 1.7.1
- Online documentation and vignettes at mc-stan.org/bayesplot
- bayesplot theme set to bayesplot::theme_default()
   * Does _not_ affect other ggplot2 plots
   * See ?bayesplot_theme_set for details on theme setting

********************************************************
Note: As of version 1.0.0, cowplot does not change the
  default ggplot2 theme anymore. To recover the previous
  behavior, execute:
  theme_set(theme_cowplot())
********************************************************

Attaching package: ‘cowplot’

The following object is masked from ‘package:ggpubr’:

    get_legend

Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Calls: data.frame -> as.matrix -> as.matrix.default -> array
Execution halted

> if(covariate_size_effects_error != 0){
+   stop(sprintf("Error while plotting covariate size effects! Code: %d", covariate_size_effects_error))
+ }
Error in eval(ei, envir) : 
  Error while plotting covariate size effects! Code: 1

**Comment by s-mishra** [comment]
Hi @Kumereng, on Mac stan has issues. Please see in here https://github.com/stan-dev/rstan/wiki/Catalina-problems
Best option would be to use our docker or use envionmnet.yml and create the enviornment using conda

**Comment by Sjors** [comment]
Another option is to run in a linux virtual machine, though no idea how efficient that is.
