### ISSUE TITLE
Request for code for report 9

### ISSUE THREAD

**Issue by mikehearn** [ImperialCollegeLondon/covid19model#89]
This code is for report 13 and appears to be different to the code used to generate the famous Report 9, from the 16th March:

https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf

This codebase is written mostly in R, but in tweets Prof Neil Ferguson claimed that the code used for this report was "thousands of lines of C". There's no C anywhere in this codebase.

I think what people would most appreciate seeing is the model that drove the UK's sudden change of tactics, which this one doesn't appear to be. Can you please publish Prof Ferguson's original code as well?

**Comment by s-mishra** [comment]
Hi @mikehearn, we clearly state this code base is for Report 13 not Report 9.  Neil is getting his code ready to be used by others, please talk to him about this.
