### ISSUE TITLE
Graphs & csv files only with data up to 24/4

### ISSUE THREAD

**Issue by pinanunes** [ImperialCollegeLondon/covid19model#90]
**Describe the bug**
Data presented on country graphs on website and csv files only with model run up to the 24th of April (is not the fetch code, that works great, is it the N2 variable?).
**To Reproduce**
Open website

**Expected behavior**
Previous models used data up to last available date

**Screenshots**

**Desktop (please complete the following information):**
Any, just reporting an issue with data on website.

**Additional context**
Didn't run the model locally, just the fetch data code.

**Comment by s-mishra** [comment]
Hi @pinanunes , thanks for pointing out. Actually our batch job crashed which meant the upload did run of earlier date. give me 3 hrs to get the manual upload done.

**Comment by s-mishra** [comment]
Website updated with correct data
