### ISSUE TITLE
Increasing N does not produce longer prediction plot

### ISSUE THREAD

**Issue by Sjors** [ImperialCollegeLondon/covid19model#92]
By default the model only produces plots with predictions for a few days:

![Netherlands_forecast_base-2006729-stanfit Rdata](https://user-images.githubusercontent.com/10217/80532397-6031c780-899c-11ea-99a2-189b176873d2.png)

I tried increasing `N2` to 200 (days?) as suggested here:

https://github.com/ImperialCollegeLondon/covid19model/blob/6ee3010a58a57cc14a16545ae897ca668b7c9096/base.r#L61

But that had no effect on the charts.

Is there something else I need to change?

**Comment by s-mishra** [comment]
Hi @Sjors, Code does produce more predictions by increasing N2. However it only produces figures for 7 day forecast. You can directly get this from stan output or in forecast prediction you will need to chnage the  code to plot more than 7 days.

**Comment by Sjors** [comment]
Thanks, I suppose that's this line?

https://github.com/ImperialCollegeLondon/covid19model/blob/da9a8a9eb853ec60cd19d40c1293db72884dfb25/plot-forecast.r#L28

**Comment by s-mishra** [comment]
Hi @Sjors, you will need to do more chnage line 71 and 73 too.
https://github.com/ImperialCollegeLondon/covid19model/blob/da9a8a9eb853ec60cd19d40c1293db72884dfb25/plot-forecast.r#L71
https://github.com/ImperialCollegeLondon/covid19model/blob/da9a8a9eb853ec60cd19d40c1293db72884dfb25/plot-forecast.r#L73

**Comment by s-mishra** [comment]
And just to say we do not endorse long-run forecasts.

**Comment by Sjors** [comment]
I understand that, but there's some people who don't, so I want to make a few plots to illustrate exactly that point.
